baseurl: /
languageCode: en-us
title: GuoQin's website
theme: hugo-ivy
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    
    - name: Home
      url: https://guoqin77.netlify.app
      weight:1
    - name: About
      url: /about/
      weight:2
   
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Welcome to my website!
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
 

