baseurl: /
languageCode: en-us
title: GuoQin's website
theme: hugo-ivy
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    
   
    - name: About
      url: /about/
      
    - name: Home
      url: /post/2022-10-16-myblog/index/
      
   
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Welcome to my website!
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
 

